[package]
name = "create-account"
version = "0.1.0"
edition = "2021"
authors = ["FlutureCode"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
